# ---
# name: Build
# on:
#   push:
#     branches: [main]
#   workflow_dispatch:
# env:
#   REGISTRY: ghcr.io
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     permissions:
#       packages: write
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Use Node.js Current
#         uses: actions/setup-node@v2
#         with:
#           node-version: 16.x
#       - name: Restore cached dependencies
#         uses: actions/cache@v2
#         with:
#           path: node_modules
#           key: node-modules-${{ hashFiles('package.json') }}
#       - name: Install dependencies
#         run: |
#           echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
#           echo PACKAGE_VERSION=$(cat package.json | jq -r '.version') >> $GITHUB_ENV
#           echo BUILD_DATE=$(date +%Y%m%d.%H%M) >> $GITHUB_ENV
#           npm install
#       - name: Test code
#         run: npm run test:ci
#       - name: Lint code
#         run: npm run lint
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       - name: Log in to GitHub Docker Registry
#         uses: docker/login-action@v1
#         with:
#           registry: ${{ env.REGISTRY }}
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ${{ secrets.AWS_REGION }}
#       - name: Login to Amazon ECR
#         uses: aws-actions/amazon-ecr-login@v1
#       - name: Build Image
#         uses: docker/build-push-action@v2
#         with:
#           push: true
#           context: .
#           tags: |
#             ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/lambda:${{ env.PACKAGE_VERSION }}
#             ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/lambda:${{ env.BUILD_DATE }}
#             ${{ env.REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/lambda:latest
#             ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.AWS_ECR_REPOSITORY }}:latest
#           labels: |
#             org.opencontainers.image.source=https://github.com/${{ github.repository }}
